export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const COOKING_CREATE_BEGIN = "COOKING_CREATE_BEGIN";
export const COOKING_CREATE_SUCCESS = "COOKING_CREATE_SUCCESS";
export const COOKING_CREATE_ERROR = "COOKING_CREATE_ERROR";

export const CLEART_ALERT = "CLEAR_ALERT";

export const COOKING_GET_BY_CATES_BEGIN = "COOKING_GET_BY_CATES_BEGIN";
export const COOKING_GET_BY_CATES_SUCCESS = "COOKING_GET_BY_CATES_SUCCESS";
export const COOKING_GET_BY_CATES_ERROR = "COOKING_GET_BY_CATES_ERROR";
